### ISSUE TITLE
lastfm is scrobbling 3 times

### ISSUE THREAD

**Issue by smoresivy** [PKBeam/AMWin-RP#52]
![Screenshot 2023-09-26 144120](https://github.com/PKBeam/AMWin-RP/assets/99206101/0d2d9957-4620-4ef9-bbba-8d05becb87b5)

**Comment by Celticsgreen** [comment]
any word on this? it almost happens to me with every scrobble. its so annoying and depressing I don't even feel like scrobbling or listening to music. AMW used to work so well for me :(

**Comment by PKBeam** [comment]
I can't reproduce this on my end so it's really hard for me to fix it. 

Work is taking up most of my spare time but if anyone else wants to open a PR I'll gladly review it.

**Comment by rinanir-cell** [comment]
I am not sure if this is helpful to anybody. I run Apple Music 1.5.0.155 (1.1280.39681.0) & AMWin-RP v1.4.9. 
All songs are being scrobbled 5 times. 

[2024-10-17.log](https://github.com/user-attachments/files/17408040/2024-10-17.log)

**Comment by loganteo** [comment]
my duplicate scrobbles showed up like this in the log:
```
[19:46:00] [Last.FM scrobbler] Scrobbling: Peach PitPeach PitSweet FA - EP
[19:46:01] [Last.FM scrobbler] An error occurred while scrobbling: System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.HashSet`1.Remove(T item)
   at IF.Lastfm.Core.Scrobblers.MemoryScrobbler.RemoveFromCacheAsync(ICollection`1 scrobbles)
   at IF.Lastfm.Core.Scrobblers.ScrobblerBase.ScrobbleAsyncInternal(IEnumerable`1 scrobbles)
   at AMWin_RichPresence.AppleMusicLastFmScrobbler.ScrobbleSong(String artist, String album, String song)
   at AMWin_RichPresence.AppleMusicScrobbler`1.Scrobbleit(AppleMusicInfo info)
[19:46:05] Set Discord RP to:
[AppleMusicInfo] Peach Pit by Peach Pit on Sweet FA - EP
| Album art: https://lastfm.freetls.fastly.net/i/u/300x300/a35e4bc333a023345404d249b9e044f9.jpg
[19:46:05] [Last.FM scrobbler] Scrobbling: Peach PitPeach PitSweet FA - EP
[19:46:05] [Last.FM scrobbler] An error occurred while scrobbling: System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.HashSet`1.Remove(T item)
   at IF.Lastfm.Core.Scrobblers.MemoryScrobbler.RemoveFromCacheAsync(ICollection`1 scrobbles)
   at IF.Lastfm.Core.Scrobblers.ScrobblerBase.ScrobbleAsyncInternal(IEnumerable`1 scrobbles)
   at AMWin_RichPresence.AppleMusicLastFmScrobbler.ScrobbleSong(String artist, String album, String song)
   at AMWin_RichPresence.AppleMusicScrobbler`1.Scrobbleit(AppleMusicInfo info)
[19:46:10] Set Discord RP to:
[AppleMusicInfo] Peach Pit by Peach Pit on Sweet FA - EP
| Album art: https://lastfm.freetls.fastly.net/i/u/300x300/a35e4bc333a023345404d249b9e044f9.jpg
[19:46:10] [Last.FM scrobbler] Scrobbling: Peach PitPeach PitSweet FA - EP
[19:46:15] Set Discord RP to:
[AppleMusicInfo] Peach Pit by Peach Pit on Sweet FA - EP
| Album art: https://lastfm.freetls.fastly.net/i/u/300x300/a35e4bc333a023345404d249b9e044f9.jpg
```

here's the [full log file](https://github.com/user-attachments/files/18396694/2025-01-07.log), pretty sure duplicates only started at line 25,590 (the last 3 songs). When I was listening to the first one, I was skipping back and forth by clicking on the lyrics if that matters. I also changed the title & artist to the original language, thus no search results in the log, but there weren't scrobbling issues before. Coincidentally, the scrobbling info was wrong this time, making the album title "album title+ artist", and it got scrobbled 2 times. The next song was played normally and got 3 scrobbles, and I cut the last song short and got 2 scrobbles.

**Comment by cjvinet** [comment]
Any update on this, it seems to be happening to me on and off, and it's wack having to go back into my Lastfm profile to delete the duplicates.
