### ISSUE TITLE
Latest version doesn't work

### ISSUE THREAD

**Issue by Strawberry015** [PKBeam/AMWin-RP#64]
v.1.2.6 never gets to run, which leaves me without a log file in the appdata folder, so I can't attach it here

I've tried downloading the previous version, v1.2.5, and this one does open and works, it just doesn't show the album cover in my account, what can I do to get the latest version to work?

**Comment by PKBeam** [comment]
Please open Event Viewer, go to Windows Logs -> Application and check for any error events logged by AMWin-RP.

**Comment by SmartBaby625** [comment]
I had the exact same issue, I checked Logs, it had an info log and two error logs (any personal info e.g. computer name, time (because of timezone and therefore location) has been replaced with asterisks):

Info Log:
```Log Name:      Application
Source:        Windows Error Reporting
Date:          5*************M
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      A*****************p
Description:
Fault bucket 2198187859040585925, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: AMWin-RichPresence.exe
P2: 1.2.6.0
P3: 641ddb2e
P4: KERNELBASE.dll
P5: 10.0.22000.2538
P6: 06aca232
P7: e0434352
P8: 0000000000052bdc
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0407a68e-4b09-43f3-9976-81a274e55387.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.96fad447-711b-47a1-9ee7-975c61080f02.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.63c7f46c-aa0a-4f9e-910a-6f9a9ab255cd.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.3a6fd510-22e8-4318-aef7-3916c085f8cc.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.463d9e45-2f8c-4c22-b169-5c8ad6b4530b.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_AMWin-RichPresen_47831b757cb5e9aad92e10825e13eca198567b9_6d0db601_7e50ee79-042e-402f-a105-6d1bf839ddf4

Analysis symbol: 
Rechecking for solution: 0
Report Id: 2b3521ad-23db-4ed1-b8fe-f8d09fdb946a
Report Status: 268435456
Hashed bucket: 3e84b71b5e67d32e2e81883617b0c8c5
Cab Guid: 0
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2*************Z" />
    <EventRecordID>190548</EventRecordID>
    <Correlation />
    <Execution ProcessID="23364" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>A**************p</Computer>
    <Security />
  </System>
  <EventData>
    <Data>2198187859040585925</Data>
    <Data>4</Data>
    <Data>APPCRASH</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>AMWin-RichPresence.exe</Data>
    <Data>1.2.6.0</Data>
    <Data>641ddb2e</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.22000.2538</Data>
    <Data>06aca232</Data>
    <Data>e0434352</Data>
    <Data>0000000000052bdc</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.0407a68e-4b09-43f3-9976-81a274e55387.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.96fad447-711b-47a1-9ee7-975c61080f02.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.63c7f46c-aa0a-4f9e-910a-6f9a9ab255cd.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.3a6fd510-22e8-4318-aef7-3916c085f8cc.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.463d9e45-2f8c-4c22-b169-5c8ad6b4530b.tmp.txt</Data>
    <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_AMWin-RichPresen_47831b757cb5e9aad92e10825e13eca198567b9_6d0db601_7e50ee79-042e-402f-a105-6d1bf839ddf4</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>2b3521ad-23db-4ed1-b8fe-f8d09fdb946a</Data>
    <Data>268435456</Data>
    <Data>3e84b71b5e67d32e2e81883617b0c8c5</Data>
    <Data>0</Data>
  </EventData>
</Event> 
```
Error Log #1:
```
Log Name:      Application
Source:        Application Error
Date:          ****************
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      A******************p
Description:
Faulting application name: AMWin-RichPresence.exe, version: 1.2.6.0, time stamp: 0x641ddb2e
Faulting module name: KERNELBASE.dll, version: 10.0.22000.2538, time stamp: 0x06aca232
Exception code: 0xe0434352
Fault offset: 0x0000000000052bdc
Faulting process ID: 0x629c
Faulting application start time: 0x01da2720e58bc613
Faulting application path: C:\Users\*****\Downloads\AMWin-RichPresence-v1.2.6\AMWin-RichPresence.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: 2b3521ad-23db-4ed1-b8fe-f8d09fdb946a
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2******************Z" />
    <EventRecordID>190547</EventRecordID>
    <Correlation />
    <Execution ProcessID="23364" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>A*******************p</Computer>
    <Security />
  </System>
  <EventData>
    <Data>AMWin-RichPresence.exe</Data>
    <Data>1.2.6.0</Data>
    <Data>641ddb2e</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.22000.2538</Data>
    <Data>06aca232</Data>
    <Data>e0434352</Data>
    <Data>0000000000052bdc</Data>
    <Data>629c</Data>
    <Data>01da2720e58bc613</Data>
    <Data>C:\Users\*****\Downloads\AMWin-RichPresence-v1.2.6\AMWin-RichPresence.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>2b3521ad-23db-4ed1-b8fe-f8d09fdb946a</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```
Error Log #2 
```
Log Name:      Application
Source:        .NET Runtime
Date:          5**************M
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      A****************p
Description:
Application: AMWin-RichPresence.exe
CoreCLR Version: 7.0.523.17405
.NET Version: 7.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\*****\AppData\Local\AMWin-RichPresence'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at AMWin_RichPresence.Logger..ctor()
   at AMWin_RichPresence.App..ctor()
   at AMWin_RichPresence.App.Main()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2*****************Z" />
    <EventRecordID>190546</EventRecordID>
    <Correlation />
    <Execution ProcessID="25244" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>A******************p</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: AMWin-RichPresence.exe
CoreCLR Version: 7.0.523.17405
.NET Version: 7.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\*****\AppData\Local\AMWin-RichPresence'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at AMWin_RichPresence.Logger..ctor()
   at AMWin_RichPresence.App..ctor()
   at AMWin_RichPresence.App.Main()
</Data>
  </EventData>
</Event>
```

**Comment by Strawberry015** [comment]
> Please open Event Viewer, go to Windows Logs -> Application and check for any error events logged by AMWin-RP.

I just checked and there are two of them, the first one is called .NET Runtime, and the another one is called Application Error, but I'm not really sure how can I send them...

**Comment by PKBeam** [comment]
I'll release a new version with the fix soon, but in the meantime the workaround is to create the folder

`C:\Users\your_username\AppData\Local\AMWin-RichPresence`

**Comment by Strawberry015** [comment]
Thanks!
