### ISSUE TITLE
Crashes after pausing music

### ISSUE THREAD

**Issue by CanOfPepsii** [PKBeam/AMWin-RP#68]
**Version Info**
v1.2.6.2

**Describe the bug**
After pausing a song that is playing, the application crashes/closes.

**Log Files**
[2023-12-13.log](https://github.com/PKBeam/AMWin-RP/files/13660223/2023-12-13.log)

**Comment by PKBeam** [comment]
Can you open Event Viewer and check under Windows Logs > Application for any .NET Runtime errors from AMWin-RP?

**Comment by CanOfPepsii** [comment]
Application: AMWin-RichPresence.exe
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException: The process cannot access the file 'C:\Users\GT-R\AppData\Local\AMWin-RichPresence\2023-12-13.log' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at AMWin_RichPresence.Logger.Log(String msg)
   at AMWin_RichPresence.Logger.Trace(String message, Object[] args)
   at DiscordRPC.IO.ManagedNamedPipeClient.EndReadStream(IAsyncResult callback)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
